[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26207b2e7576f35ca95eb5d1dc88fdeddc3f9954"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "0bc3ee8ddbfbbcd0fd40306d07d6e64ee37c89f657fe09f52067e232319ca66c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e14308ee06465e2a9047efc5290bed3fb3b6071c"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "6982883863f90324e6c131e057ce8aa89ff9efc92df025a08c865439e9a6885f"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efc675377bf48b8b218e07b211c73a912f17cc2d"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "656f10fa379d3dda3ba403c7855dbf3e00c633178b33cabe37c8efb29969cc3b"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a423ab12cf42b47dcee2fb2ab1283d27bea160b"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "a34539d4d2067fa5962051f585518ad14f53f1721100db907f6374794cadc1e7"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a61ff9fa11fb45273ef54c447ed5b5809ecf5c7"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "72c63842d4f42f30903a4f40ed1479e853478cb76c25129598ef5cf0d0f1705c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b0a408a59dd79f50f0fd4884a2df96508eb054f"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "0d0602431e937940c4c068d2423e7f99b84f0bd4f094e29da29e0fc34a37eb6e"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7399d281ff8027ee5bfafc5d4646f4dcacc5360d"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "4df07cc35af4248220c774f2bfa0ccdf777500fc93e40e41a5b182b83bf6d29d"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7187b2db1bcf22b029485d4783ca03fdf5fcfe8"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "d16fbc440c57385eb44eb3339156eaadf8ca5edaf1c71f8645fae36d1115b53c"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29255e77773ac53d4c02b23cb3cfdc56bd3b36c7"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "44f62eaf748cee357a662334032ad89a3d23670f97851b537660d50321e27599"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb14b0597e638068a6d8b5c2b56cd961352c758f"
julia_version = "1.10.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "0089056ff17f199658b1b7c6f76efd6631d675232c001b3ae29763b2054f4814"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae9710dd766074f974df38136f795a69e775749e"
julia_version = "1.11.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "053bac2903cca5bf3458e7521d86083f98d6af7aa32548bcf27f9551cbf880da"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f59e1d43c40e3d1616295c2f9362db02ead670b2"
julia_version = "1.12.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "7a57b158f275c62af8b6ac719f0aef865021daa3a4abb1a088e504b8f07ae2e9"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.4+0/voropp_wrapper.v0.1.4.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
