[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "904e86c09f30d81696389683982c58a1469fb89c"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "61f0568b3944352c9b2278683b4489dda721fd5b95c206a2796dccaf6f7e3fcf"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12aed7eef380a077bd86dcd30fbda8d1960a3a77"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "590306ea45997455e1037e11dfb0b2ab73acb6f6de2dc83dfaf8c0215cc1d8cf"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77294b1de4bb87f4b56a40243cb7354d978f2f2b"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "502ca1ed3172d13422d3dac3584fc4f70f068d6d239a59e60683c643af0a3a07"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b96c52e02545ee1baa6683c28702fd19504576a0"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "d400396fe660d17bdc0ec953fc3401f44a051532dacc86a11a9f7ccdbff0e602"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.i686-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "daba87b99179f7287234173441a91c52c2a9acb8"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "3bf19eed2654ff7a8177adfe541edc8d5acc941d2451f4784c48f87c99836577"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.i686-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a93866d31d74b61a5ab9808352e05255f5e1c45a"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "8c1084a5d82aa09f60a3720a1ce179c4d961412a5928db98f698ce162f9174a5"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.i686-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e33ff34c40b35e010518a8efb82ae9e105f8768e"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "f67a5f4c3580d30288985d6f8daa6b7bda9ac05b344626ed28e15ce2f07288fd"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ba5bbfad0ff0c28965a718f90fda84f94b9e267"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "ac51a843cae2a57f4cde11793f9f7c846790c63b4704e22ea6a6f9d787fffeb8"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725de7636e316ecaef203a03751e01873a54b0d3"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[voropp_wrapper.download]]
    sha256 = "3c0a4c2920fa6be891f5a098508444dd6e2206f30db936388713852548b03869"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57605f4950951eac5deba62b634f6acd4b5e4bd4"
julia_version = "1.10.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "831997715311761a7ebffb56a466d1c2ba6c7edf8cf85d53cd6c34f4da577463"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13318e8753b55850d0a8a329669c0af2e11447e1"
julia_version = "1.11.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "65251e725a0c1819817b95194cbf34b9f3cb5cf7a6eff9a83651c60cc851ed54"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[voropp_wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8d06fa770c73b739e9b329b3a891101dfcf490"
julia_version = "1.12.0"
os = "windows"

    [[voropp_wrapper.download]]
    sha256 = "5a33849ca5c8f6a27d034cdb27352a37d3a355e1147dcdcf142d2785c40baa6f"
    url = "https://github.com/vvpisarev/voropp_wrapper_jll.jl/releases/download/voropp_wrapper-v0.1.3+0/voropp_wrapper.v0.1.3.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
