name = "voropp_wrapper_jll"
uuid = "5cd5a5c3-8aac-5681-ad41-71fcd0ac50f1"
version = "0.1.3+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
libcxxwrap_julia_jll = "0.14"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
